title: "My Portfolio"
theme: minima
description: "A showcase of my programming and audio/video projects"
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/jekyll/jekyll" }
    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }
author:
  name: Jonah Watts
  email: "jonahwatts@gmail.com"