title: "Jonah Watts"
remote_theme: jekyll/minima
description: "A showcase of my programming and audio/video projects"
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/adastorm" }
  skin: dark
header_pages:
  - audio-video.md
  - programming.md
  - resume.md

author:
  name: Jonah Watts
  email: "Jonah.watts@gmail.com"